var jsonData =  {
 "data": [
 {
 "Measurement": [ "Ambiguity" ],
"Type": [ "Analog" ],
"Type Short": [ "AN" ],
"N": [ "3" ],
"Minimum": [ "-0.56" ],
"Maximum": [ "0.33" ],
"Mean": [ "-0.05" ],
"SD": [ "0.46" ],
"SE of Mean": [ "-0.03" ],
"Lower CI": [ "-0.89" ],
"Upper CI": [ "1.26" ],
"Skewness": [ "-0.25" ],
"Kurtosis": [ "-2.33" ],
"KS Test D": [ "0.37" ],
"KS Test P Value": [ "0.68" ],
"Paired-t Test": [ "-0.46" ],
"P Value": [ "0.69" ] 
},
{
 "Measurement": [ "Ambiguity" ],
"Type": [ "Digital" ],
"Type Short": [ "DI" ],
"N": [ "3" ],
"Minimum": [ "-0.14" ],
"Maximum": [ "0.67" ],
"Mean": [ "0.18" ],
"SD": [ "0.43" ],
"SE of Mean": [ "0.1" ],
"Lower CI": [ "-0.62" ],
"Upper CI": [ "1.5" ],
"Skewness": [ "0.34" ],
"Kurtosis": [ "-2.33" ],
"KS Test D": [ "0.44" ],
"KS Test P Value": [ "0.47" ],
"Paired-t Test": [ "-0.46" ],
"P Value": [ "0.69" ] 
},
{
 "Measurement": [ "Linking" ],
"Type": [ "Analog" ],
"Type Short": [ "AN" ],
"N": [ "3" ],
"Minimum": [ "0.33" ],
"Maximum": [ "1" ],
"Mean": [ "0.55" ],
"SD": [ "0.39" ],
"SE of Mean": [ "0.32" ],
"Lower CI": [ "-0.16" ],
"Upper CI": [ "0.79" ],
"Skewness": [ "0.38" ],
"Kurtosis": [ "-2.33" ],
"KS Test D": [ "0.63" ],
"KS Test P Value": [ "0.19" ],
"Paired-t Test": [ "1.73" ],
"P Value": [ "0.23" ] 
},
{
 "Measurement": [ "Linking" ],
"Type": [ "Digital" ],
"Type Short": [ "DI" ],
"N": [ "3" ],
"Minimum": [ "-0.33" ],
"Maximum": [ "1" ],
"Mean": [ "0.22" ],
"SD": [ "0.69" ],
"SE of Mean": [ "0.13" ],
"Lower CI": [ "-1.05" ],
"Upper CI": [ "1.25" ],
"Skewness": [ "0.29" ],
"Kurtosis": [ "-2.33" ],
"KS Test D": [ "0.37" ],
"KS Test P Value": [ "0.68" ],
"Paired-t Test": [ "1.73" ],
"P Value": [ "0.23" ] 
},
{
 "Measurement": [ "Justification" ],
"Type": [ "Analog" ],
"Type Short": [ "AN" ],
"N": [ "3" ],
"Minimum": [ "0.25" ],
"Maximum": [ "0.33" ],
"Mean": [ "0.3" ],
"SD": [ "0.05" ],
"SE of Mean": [ "0.18" ],
"Lower CI": [ "0.24" ],
"Upper CI": [ "1" ],
"Skewness": [ "-0.38" ],
"Kurtosis": [ "-2.33" ],
"KS Test D": [ "0.6" ],
"KS Test P Value": [ "0.23" ],
"Paired-t Test": [ "-2.49" ],
"P Value": [ "0.13" ] 
},
{
 "Measurement": [ "Justification" ],
"Type": [ "Digital" ],
"Type Short": [ "DI" ],
"N": [ "3" ],
"Minimum": [ "0.56" ],
"Maximum": [ "1" ],
"Mean": [ "0.72" ],
"SD": [ "0.24" ],
"SE of Mean": [ "0.42" ],
"Lower CI": [ "-0.03" ],
"Upper CI": [ "1.39" ],
"Skewness": [ "0.37" ],
"Kurtosis": [ "-2.33" ],
"KS Test D": [ "0.71" ],
"KS Test P Value": [ "0.05" ],
"Paired-t Test": [ "-2.49" ],
"P Value": [ "0.13" ] 
},
{
 "Measurement": [ "Critical Assessment" ],
"Type": [ "Analog" ],
"Type Short": [ "AN" ],
"N": [ "3" ],
"Minimum": [ "0.33" ],
"Maximum": [ "1" ],
"Mean": [ "0.61" ],
"SD": [ "0.35" ],
"SE of Mean": [ "0.35" ],
"Lower CI": [ "1" ],
"Upper CI": [ "1.26" ],
"Skewness": [ "0.28" ],
"Kurtosis": [ "-2.33" ],
"KS Test D": [ "0.63" ],
"KS Test P Value": [ "0.11" ],
"Paired-t Test": [ "-1.94" ],
"P Value": [ "0.19" ] 
},
{
 "Measurement": [ "Critical Assessment" ],
"Type": [ "Digital" ],
"Type Short": [ "DI" ],
"N": [ "3" ],
"Minimum": [ "1" ],
"Maximum": [ "1" ],
"Mean": [ "1" ],
"SD": [ "0" ],
"SE of Mean": [ "0.58" ],
"Lower CI": [ "-0.73" ],
"Upper CI": [ "1.06" ],
"Skewness": [ "NaN" ],
"Kurtosis": [ "NaN" ],
"KS Test D": [ "0.84" ],
"KS Test P Value": [ "0.03" ],
"Paired-t Test": [ "-1.94" ],
"P Value": [ "0.19" ] 
},
{
 "Measurement": [ "Practical Utility" ],
"Type": [ "Analog" ],
"Type Short": [ "AN" ],
"N": [ "3" ],
"Minimum": [ "0" ],
"Maximum": [ "1" ],
"Mean": [ "0.33" ],
"SD": [ "0.58" ],
"SE of Mean": [ "0.19" ],
"Lower CI": [ "-0.16" ],
"Upper CI": [ null ],
"Skewness": [ "0.38" ],
"Kurtosis": [ "-2.33" ],
"KS Test D": [ "0.5" ],
"KS Test P Value": [ "0.44" ],
"Paired-t Test": [ "-2" ],
"P Value": [ "0.18" ] 
},
{
 "Measurement": [ "Practical Utility" ],
"Type": [ "Digital" ],
"Type Short": [ "DI" ],
"N": [ "3" ],
"Minimum": [ "0.33" ],
"Maximum": [ "1" ],
"Mean": [ "0.55" ],
"SD": [ "0.39" ],
"SE of Mean": [ "0.32" ],
"Lower CI": [ "0.05" ],
"Upper CI": [ null ],
"Skewness": [ "0.38" ],
"Kurtosis": [ "-2.33" ],
"KS Test D": [ "0.63" ],
"KS Test P Value": [ "0.19" ],
"Paired-t Test": [ "-2" ],
"P Value": [ "0.18" ] 
},
{
 "Measurement": [ "Width of Knowledge" ],
"Type": [ "Analog" ],
"Type Short": [ "AN" ],
"N": [ "3" ],
"Minimum": [ "0" ],
"Maximum": [ "1" ],
"Mean": [ "0.67" ],
"SD": [ "0.58" ],
"SE of Mean": [ "0.38" ],
"Lower CI": [ "0.79" ],
"Upper CI": [ null ],
"Skewness": [ "-0.38" ],
"Kurtosis": [ "-2.33" ],
"KS Test D": [ "0.51" ],
"KS Test P Value": [ "0.42" ],
"Paired-t Test": [ "0.56" ],
"P Value": [ "0.63" ] 
},
{
 "Measurement": [ "Width of Knowledge" ],
"Type": [ "Digital" ],
"Type Short": [ "DI" ],
"N": [ "3" ],
"Minimum": [ "0" ],
"Maximum": [ "1" ],
"Mean": [ "0.44" ],
"SD": [ "0.51" ],
"SE of Mean": [ "0.26" ],
"Lower CI": [ "0.97" ],
"Upper CI": [ null ],
"Skewness": [ "0.21" ],
"Kurtosis": [ "-2.33" ],
"KS Test D": [ "0.5" ],
"KS Test P Value": [ "0.33" ],
"Paired-t Test": [ "0.56" ],
"P Value": [ "0.63" ] 
} 
] 
}