var jsonData =  {
 "data": [
 {
 "Row": "1",
"Column": "2",
"Row Variable": "Create Points AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "3",
"Row Variable": "Create Points AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "4",
"Row Variable": "Create Points AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "5",
"Row Variable": "Create Points AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "6",
"Row Variable": "Create Points AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "7",
"Row Variable": "Create Points AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "8",
"Row Variable": "Create Points AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "9",
"Row Variable": "Create Points AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "10",
"Row Variable": "Create Points AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.94",
"P-value": "0.21",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "11",
"Row Variable": "Create Points AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "12",
"Row Variable": "Create Points AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "13",
"Row Variable": "Create Points AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "14",
"Row Variable": "Create Points AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "15",
"Row Variable": "Create Points AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "16",
"Row Variable": "Create Points AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "17",
"Row Variable": "Create Points AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "18",
"Row Variable": "Create Points AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "1",
"Column": "19",
"Row Variable": "Create Points AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "1",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "3",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "4",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "5",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "6",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "7",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "8",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "9",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "10",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "11",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "12",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "13",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "14",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "15",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "16",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "17",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "18",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "2",
"Column": "19",
"Row Variable": "Attach Sources AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "1",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "2",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "4",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "5",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "6",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "7",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "8",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "9",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "10",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.76",
"P-value": "0.45",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "11",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "12",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "13",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "14",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "15",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "16",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "17",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "18",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "3",
"Column": "19",
"Row Variable": "Organizing Points AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "1",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "2",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "3",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "5",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "6",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "7",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "8",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "9",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "10",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.76",
"P-value": "0.45",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "11",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "12",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "13",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "14",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "15",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "16",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "17",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "18",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "4",
"Column": "19",
"Row Variable": "View Others Points AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "1",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "2",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "3",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "4",
"Row Variable": "Explain Points AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "6",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "7",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "8",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "9",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "10",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.33",
"P-value": "0.79",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "11",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "12",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "13",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "14",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "15",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "16",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "17",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "18",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "5",
"Column": "19",
"Row Variable": "Explain Points AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "1",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "2",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "3",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "4",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "5",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "7",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "8",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "9",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "10",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.76",
"P-value": "0.45",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "11",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "12",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "13",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "14",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "15",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "16",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "17",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "18",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "6",
"Column": "19",
"Row Variable": "Show Sources to Others AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "1",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "2",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "3",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "4",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "5",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "6",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "8",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "9",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "10",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.98",
"P-value": "0.12",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "11",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "12",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "13",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "14",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "15",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "16",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "17",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "18",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "7",
"Column": "19",
"Row Variable": "Understand Others Points AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "1",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "2",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "3",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "4",
"Row Variable": "Edit Points AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "5",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "6",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "7",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "9",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "10",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.98",
"P-value": "0.12",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "11",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "12",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "13",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "14",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "15",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "16",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "17",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "18",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "8",
"Column": "19",
"Row Variable": "Edit Points AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "1",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "2",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "3",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "4",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "5",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "6",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "7",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "8",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "10",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "11",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "12",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "13",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "14",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "15",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "16",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "17",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "18",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "9",
"Column": "19",
"Row Variable": "Collaborative Affinity Diagram AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "1",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.94",
"P-value": "0.21",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "2",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "3",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.76",
"P-value": "0.45",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "4",
"Row Variable": "Save to Report AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.76",
"P-value": "0.45",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "5",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.33",
"P-value": "0.79",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "6",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.76",
"P-value": "0.45",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "7",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.98",
"P-value": "0.12",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "8",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.98",
"P-value": "0.12",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "9",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "11",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "12",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.33",
"P-value": "0.79",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "13",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "14",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "15",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "16",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "17",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "18",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.98",
"P-value": "0.12",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "10",
"Column": "19",
"Row Variable": "Save to Report AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.94",
"P-value": "0.21",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "1",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "2",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "3",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "4",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "5",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "6",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "7",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "8",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "9",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "10",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "12",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "13",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "14",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "15",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "16",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "17",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "18",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "11",
"Column": "19",
"Row Variable": "Understand Report and Continue AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "1",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "2",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "3",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "4",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "5",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "6",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "7",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "8",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "9",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "10",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.33",
"P-value": "0.79",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "11",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "13",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "14",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "15",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "16",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "17",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "18",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "12",
"Column": "19",
"Row Variable": "Confidence of Points AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "1",
"Row Variable": "Usability AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "2",
"Row Variable": "Usability AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "3",
"Row Variable": "Usability AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "4",
"Row Variable": "Usability AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "5",
"Row Variable": "Usability AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "6",
"Row Variable": "Usability AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "7",
"Row Variable": "Usability AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "8",
"Row Variable": "Usability AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "9",
"Row Variable": "Usability AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "10",
"Row Variable": "Usability AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "11",
"Row Variable": "Usability AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "12",
"Row Variable": "Usability AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "14",
"Row Variable": "Usability AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "15",
"Row Variable": "Usability AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "16",
"Row Variable": "Usability AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "17",
"Row Variable": "Usability AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "18",
"Row Variable": "Usability AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "13",
"Column": "19",
"Row Variable": "Usability AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "1",
"Row Variable": "Clarity AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "2",
"Row Variable": "Clarity AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "3",
"Row Variable": "Clarity AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "4",
"Row Variable": "Clarity AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "5",
"Row Variable": "Clarity AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "6",
"Row Variable": "Clarity AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "7",
"Row Variable": "Clarity AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "8",
"Row Variable": "Clarity AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "9",
"Row Variable": "Clarity AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "10",
"Row Variable": "Clarity AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "11",
"Row Variable": "Clarity AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "12",
"Row Variable": "Clarity AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "13",
"Row Variable": "Clarity AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "15",
"Row Variable": "Clarity AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "16",
"Row Variable": "Clarity AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "17",
"Row Variable": "Clarity AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "18",
"Row Variable": "Clarity AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "14",
"Column": "19",
"Row Variable": "Clarity AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "1",
"Row Variable": "Functions AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "2",
"Row Variable": "Functions AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "3",
"Row Variable": "Functions AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "4",
"Row Variable": "Functions AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "5",
"Row Variable": "Functions AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "6",
"Row Variable": "Functions AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "7",
"Row Variable": "Functions AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "8",
"Row Variable": "Functions AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "9",
"Row Variable": "Functions AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "10",
"Row Variable": "Functions AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "11",
"Row Variable": "Functions AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "12",
"Row Variable": "Functions AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "13",
"Row Variable": "Functions AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "14",
"Row Variable": "Functions AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "16",
"Row Variable": "Functions AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "17",
"Row Variable": "Functions AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "18",
"Row Variable": "Functions AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "15",
"Column": "19",
"Row Variable": "Functions AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "1",
"Row Variable": "Depth AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "2",
"Row Variable": "Depth AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "3",
"Row Variable": "Depth AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "4",
"Row Variable": "Depth AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "5",
"Row Variable": "Depth AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "6",
"Row Variable": "Depth AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "7",
"Row Variable": "Depth AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "8",
"Row Variable": "Depth AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "9",
"Row Variable": "Depth AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "10",
"Row Variable": "Depth AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "11",
"Row Variable": "Depth AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "12",
"Row Variable": "Depth AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "13",
"Row Variable": "Depth AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "14",
"Row Variable": "Depth AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "15",
"Row Variable": "Depth AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "17",
"Row Variable": "Depth AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "18",
"Row Variable": "Depth AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "16",
"Column": "19",
"Row Variable": "Depth AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "1",
"Row Variable": "Efficient AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "2",
"Row Variable": "Efficient AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "3",
"Row Variable": "Efficient AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "4",
"Row Variable": "Efficient AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "5",
"Row Variable": "Efficient AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "6",
"Row Variable": "Efficient AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "7",
"Row Variable": "Efficient AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "8",
"Row Variable": "Efficient AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "9",
"Row Variable": "Efficient AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "10",
"Row Variable": "Efficient AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.19",
"P-value": "0.88",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "11",
"Row Variable": "Efficient AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "12",
"Row Variable": "Efficient AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "13",
"Row Variable": "Efficient AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "14",
"Row Variable": "Efficient AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "15",
"Row Variable": "Efficient AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "16",
"Row Variable": "Efficient AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "18",
"Row Variable": "Efficient AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "17",
"Column": "19",
"Row Variable": "Efficient AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "1",
"Row Variable": "Quality AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "2",
"Row Variable": "Quality AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "3",
"Row Variable": "Quality AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "4",
"Row Variable": "Quality AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "5",
"Row Variable": "Quality AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "6",
"Row Variable": "Quality AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "7",
"Row Variable": "Quality AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "8",
"Row Variable": "Quality AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "9",
"Row Variable": "Quality AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "10",
"Row Variable": "Quality AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.98",
"P-value": "0.12",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "11",
"Row Variable": "Quality AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "12",
"Row Variable": "Quality AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "13",
"Row Variable": "Quality AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "14",
"Row Variable": "Quality AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "15",
"Row Variable": "Quality AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "16",
"Row Variable": "Quality AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "17",
"Row Variable": "Quality AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "18",
"Column": "19",
"Row Variable": "Quality AN",
"Row Variable Type": "Control AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "1",
"Row Variable": "Control AN",
"Row Variable Type": "Create Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "1",
"P-value": "0",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "2",
"Row Variable": "Control AN",
"Row Variable Type": "Attach Sources AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "3",
"Row Variable": "Control AN",
"Row Variable Type": "Organizing Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "4",
"Row Variable": "Control AN",
"Row Variable Type": "View Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "5",
"Row Variable": "Control AN",
"Row Variable Type": "Explain Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "6",
"Row Variable": "Control AN",
"Row Variable Type": "Show Sources to Others AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "7",
"Row Variable": "Control AN",
"Row Variable Type": "Understand Others Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "-0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "8",
"Row Variable": "Control AN",
"Row Variable Type": "Edit Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "9",
"Row Variable": "Control AN",
"Row Variable Type": "Collaborative Affinity Diagram AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "10",
"Row Variable": "Control AN",
"Row Variable Type": "Save to Report AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.94",
"P-value": "0.21",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "11",
"Row Variable": "Control AN",
"Row Variable Type": "Understand Report and Continue AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "12",
"Row Variable": "Control AN",
"Row Variable Type": "Confidence of Points AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0",
"P-value": "1",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "13",
"Row Variable": "Control AN",
"Row Variable Type": "Usability AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "14",
"Row Variable": "Control AN",
"Row Variable Type": "Clarity AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "15",
"Row Variable": "Control AN",
"Row Variable Type": "Functions AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "16",
"Row Variable": "Control AN",
"Row Variable Type": "Depth AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "17",
"Row Variable": "Control AN",
"Row Variable Type": "Efficient AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.5",
"P-value": "0.67",
"Lower 95% CI": null,
"Upper 95% CI": null 
},
{
 "Row": "19",
"Column": "18",
"Row Variable": "Control AN",
"Row Variable Type": "Quality AN",
"Column Variable": "AN",
"Column Variable Type": "AN",
"Correlation": "0.87",
"P-value": "0.33",
"Lower 95% CI": null,
"Upper 95% CI": null 
} 
] 
}